# Lab | Hypothesis Testing

**Objective**

Welcome to the Hypothesis Testing Lab, where we embark on an enlightening journey through the realm of statistical decision-making! In this laboratory, we delve into various scenarios, applying the powerful tools of hypothesis testing to scrutinize and interpret data.

From testing the mean of a single sample (One Sample T-Test), to investigating differences between independent groups (Two Sample T-Test), and exploring relationships within dependent samples (Paired Sample T-Test), our exploration knows no bounds. Furthermore, we'll venture into the realm of Analysis of Variance (ANOVA), unraveling the complexities of comparing means across multiple groups.

So, grab your statistical tools, prepare your hypotheses, and let's embark on this fascinating journey of exploration and discovery in the world of hypothesis testing!

**Challenge 1**

In this challenge, we will be working with pokemon data. The data can be found here:

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv

In [1]:
#libraries
import pandas as pd
import scipy.stats as st
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/pokemon.csv")
df

,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...
795,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,Mega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,Hoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,Hoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

- We posit that Pokemons of type Dragon have, on average, more HP stats than Grass. Choose the propper test and, with 5% significance, comment your findings.

In [4]:
df["Type 1"].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [5]:
df["HP"].unique()

array([ 45,  60,  80,  39,  58,  78,  44,  59,  79,  50,  40,  65,  63,
        83,  30,  55,  35,  75,  70,  90,  46,  61,  81,  95,  38,  73,
       115, 140,  10,  25,  52, 105,  85, 250,  20, 130,  48, 160,  41,
        91, 106, 100, 125, 190, 255,  28,  68, 150,  31,   1,  64,  84,
       104,  72, 144, 170, 110,  43,  66,  86,  99,  76,  53,  37,  77,
        67,  97, 111,  49,  71, 103,  57, 108, 135,  74,  69, 120, 116,
        62,  54,  36,  51, 114, 165, 109,  89,  92,  56,  88, 123, 101,
        82,  42, 126])

In [6]:
cross_table1 = pd.crosstab(df["Type 1"], df["HP"])
cross_table1

HP,1,10,20,25,28,30,31,35,36,37,...,135,140,144,150,160,165,170,190,250,255
Type 1,,,,,,,,,,,,,,,,,,,,,
Bug,1,0,1,0,0,2,1,1,0,1,...,0,0,0,0,0,0,0,0,0,0
Dark,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Dragon,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Electric,0,0,1,1,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
Fairy,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Fighting,0,0,0,0,0,1,0,1,0,0,...,0,0,1,0,0,0,0,0,0,0
Fire,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Flying,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Ghost,0,0,1,0,0,1,0,0,0,0,...,0,0,0,3,0,0,0,0,0,0
Grass,0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Ground,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Ice,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Normal,0,0,0,0,0,1,0,2,0,0,...,1,1,0,1,1,0,0,0,1,1
Poison,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Psychic,0,0,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Rock,0,0,0,0,0,3,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
Steel,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Water,0,0,2,0,0,4,0,2,0,0,...,0,0,0,0,0,1,1,0,0,0

H0 -> pokemon dragon type HP = pokemon grass type HP
H1 -> pokemon dragon type HP != pokemon grass type HP

In [9]:
HP_dragon = df[df["Type 1"]=="Dragon"]["HP"]
HP_grass = df[df["Type 1"]=="Grass"]["HP"]

Usamos two-sample T test ya que son dos muestras disferentes.

In [10]:
_, p_value = st.ttest_ind(HP_dragon, HP_grass, equal_var=False)
print(p_value)

0.0015987219490841195

El valor resultado de p-value es inferior al nivel de significancia 0.05. Por lo tanto rechazamos la hipótesis nula y tomamos como válida estadísticamente la hipótesis alternativa H1. En un principio los pokemon de tipo grass si tienen más HP que los de tipo dragon.

- We posit that Legendary Pokemons have different stats (HP, Attack, Defense, Sp.Atk, Sp.Def, Speed) when comparing with Non-Legendary. Choose the propper test and, with 5% significance, comment your findings.

In [12]:
df.columns

Index(['Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [14]:
df["Legendary"].value_counts()

Legendary
False    735
True      65
Name: count, dtype: int64

H0 -> pokemon legendary stats = pokemon no legendary stats
H1 -> pokemon legendary stats != pokemon no legendary stats

In [62]:
stats_col = ["HP", "Attack", "Defense", "Sp. Atk", "Sp. Def", "Speed"]

Legendary = df[df["Legendary"] == True]

No_Legendary = df[df["Legendary"] == False]

Usamos two-sample T test ya que son dos muestras disferentes. Hacemos un for para iterar por columnas de stat.

In [63]:
for stat in stats_col:
    Legendary = df[df["Legendary"] == True][stat]
    No_Legendary = df[df["Legendary"] == False][stat]
    _, p_value = st.ttest_ind(Legendary, No_Legendary, equal_var=False)
print(p_value)

1.0490163118824585e-18

Todos los valores resultado de p-value son inferiores al nivel de significancia 0.05. Por lo tanto rechazamos la hipótesis nula y tomamos como válida estadísticamente la hipótesis alternativa H1. En un principio los pokemon de tipo lengendarios si tienen diferencias en todos sus stats comparado con los pokemon no legendarios.

**Challenge 2**

In this challenge, we will be working with california-housing data. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv

In [29]:
df2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/california_housing.csv")
df2.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [30]:
df2

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

**We posit that houses close to either a school or a hospital are more expensive.**

- School coordinates (-118, 34)
- Hospital coordinates (-122, 37)

We consider a house (neighborhood) to be close to a school or hospital if the distance is lower than 0.50.

Hint:
- Write a function to calculate euclidean distance from each house (neighborhood) to the school and to the hospital.
- Divide your dataset into houses close and far from either a hospital or school.
- Choose the propper test and, with 5% significance, comment your findings.

In [31]:
def euclidean_distance(lon1, lat1, lon2, lat2):
    return np.sqrt((lon1 - lon2)**2 + (lat1 - lat2)**2)

In [35]:
school_lon = -118
school_lat = 34

hosp_lon = -122
hosp_lat = 37

Creamos columnas que nos den el valor de cercania de escuela y hospital ( cerca si < de 0.50)

In [38]:

df2["dist_to_school"] = euclidean_distance(df2["longitude"], df2["latitude"], school_lon, school_lat)

In [51]:
df2["dist_to_hospital"] = euclidean_distance(df2["longitude"], df2["latitude"], hosp_lon, hosp_lat)

In [40]:
df2.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,dist_to_school,dist_to_hospital
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,3.694888,8.187319
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,3.552591,7.966235
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,3.453940,8.143077
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,3.448840,8.154416
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,3.456848,8.183508

In [52]:
def categorize_distance(distance):
    if distance < 0.50:
        return "close"
    else:
        return "far"

In [ ]:
df2["school_proximity"] = df2["dist_to_school"].apply(categorize_distance)

In [56]:
df2["hospital_proximity"] = df2["dist_to_hospital"].apply(categorize_distance)

In [57]:
df2.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,dist_to_school,dist_to_hospital,school_proximity,hospital_proximity
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0,3.694888,8.187319,far,far
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0,3.552591,7.966235,far,far
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0,3.453940,8.143077,far,far
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0,3.448840,8.154416,far,far
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0,3.456848,8.183508,far,far

H0 -> house close to school and hospital != expensive
H1 -> house close to school and hospital = expensive

In [58]:
far_hosp = df2[df2["hospital_proximity"]=="far"]["median_house_value"]
close_hosp = df2[df2["hospital_proximity"]=="close"]["median_house_value"]

usamos Two sample T test

In [59]:
_, p_value = st.ttest_ind(far_hosp, close_hosp, equal_var=False)
print(p_value)

2.9452293998782314e-143

In [60]:
far_school = df2[df2["school_proximity"]=="far"]["median_house_value"]
close_school = df2[df2["school_proximity"]=="close"]["median_house_value"]

In [61]:
_, p_value = st.ttest_ind(far_school, close_school, equal_var=False)
print(p_value)

7.942474204639094e-129

Todos los valores resultado de p-value tanto en escuela como en hospital son inferiores al nivel de significancia 0.05. Por lo tanto rechazamos la hipótesis nula H0 y tomamos como válida estadísticamente la hipótesis alternativa H1. En un principio las casa que estan cerca de la escuela y/o cerca del hospital no son más caras.